server:
  port: 8080
  servlet:
    context-path: "/spring"
spring:
  datasource:
    url: jdbc:mysql:///spring_senior?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl_auto: update
      hbm2ddl:
        auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true
    show-sql: true
  redis:
    host: 192.168.10.131 #配置redis地址

logging:
  level:
    root: info #日志等级

